/*
 * BEWARE BEWARE BEWARE BEWARE BEWARE BEWARE BEWARE BEWARE BEWARE
 * This file has been auto-generated by the confdc compiler.
 * Source: ../load-dir/resource-allocator.fxs
 * BEWARE BEWARE BEWARE BEWARE BEWARE BEWARE BEWARE BEWARE BEWARE
 */

package com.tailf.pkg.resourcemanager.namespaces;

import com.tailf.conf.ConfNamespace;

/** Autogenerated namespace class for YANG module resource-allocator.yang */
public class resourceAllocator extends ConfNamespace {
    public static final int hash = 988477393;
    public int hash() {
        return resourceAllocator.hash;
    }

    public static final String id = "http://tail-f.com/pkg/resource-allocator";
    public String id() {
        return resourceAllocator.id;
    }

    public static final String uri = "http://tail-f.com/pkg/resource-allocator";
    public String uri() {
        return resourceAllocator.uri;
    }

    public static final String prefix = "ralloc";
    public String prefix() {
        return resourceAllocator.prefix;
    }

    public resourceAllocator() {}

    public static int stringToHash(String str) {
        return ConfNamespace.stringToHash(str);
    }

    public static String hashToString(int hash) {
        return ConfNamespace.hashToString(hash);
    }

    public static final int    _resource_pools = 453484040;
    public static final String _resource_pools_ = "resource-pools";
}
