/*
 * BEWARE BEWARE BEWARE BEWARE BEWARE BEWARE BEWARE BEWARE BEWARE
 * This file has been auto-generated by the confdc compiler.
 * Source: ../load-dir/id-allocator.fxs
 * BEWARE BEWARE BEWARE BEWARE BEWARE BEWARE BEWARE BEWARE BEWARE
 */

package com.tailf.pkg.idallocator.namespaces;

import com.tailf.conf.ConfNamespace;

/** Autogenerated namespace class for YANG module id-allocator.yang */
public class idAllocator extends ConfNamespace {
    public static final int hash = 1335195571;
    public int hash() {
        return idAllocator.hash;
    }

    public static final String id = "http://tail-f.com/pkg/id-allocator";
    public String id() {
        return idAllocator.id;
    }

    public static final String uri = "http://tail-f.com/pkg/id-allocator";
    public String uri() {
        return idAllocator.uri;
    }

    public static final String prefix = "idalloc";
    public String prefix() {
        return idAllocator.prefix;
    }

    public idAllocator() {}

    public static int stringToHash(String str) {
        return ConfNamespace.stringToHash(str);
    }

    public static String hashToString(int hash) {
        return ConfNamespace.hashToString(hash);
    }

    public static final int    _enabled = 197426095;
    public static final String _enabled_ = "enabled";
    public static final int    _alarms = 1907669299;
    public static final String _alarms_ = "alarms";
    public static final int    _exclude = 1901477268;
    public static final String _exclude_ = "exclude";
    public static final int    _username = 870658415;
    public static final String _username_ = "username";
    public static final int    _allocating_service = 38335226;
    public static final String _allocating_service_ = "allocating-service";
    public static final int    _response = 1363637576;
    public static final String _response_ = "response";
    public static final int    _name = 1998270519;
    public static final String _name_ = "name";
    public static final int    _range = 28853268;
    public static final String _range_ = "range";
    public static final int    _end = 1510734141;
    public static final String _end_ = "end";
    public static final int    _response_choice = 523747723;
    public static final String _response_choice_ = "response-choice";
    public static final int    _ok = 410023581;
    public static final String _ok_ = "ok";
    public static final int    _request = 1788176625;
    public static final String _request_ = "request";
    public static final int    _sync = 2047869128;
    public static final String _sync_ = "sync";
    public static final int    _id = 1279252765;
    public static final String _id_ = "id";
    public static final int    _id_pool = 1249242085;
    public static final String _id_pool_ = "id-pool";
    public static final int    _stop_allocation = 1220004342;
    public static final String _stop_allocation_ = "stop-allocation";
    public static final int    _id_pool_low_threshold_reached = 463519780;
    public static final String _id_pool_low_threshold_reached_ = "id-pool-low-threshold-reached";
    public static final int    _id_allocation_alarm = 1749404686;
    public static final String _id_allocation_alarm_ = "id-allocation-alarm";
    public static final int    _id_pool_exhausted = 545098752;
    public static final String _id_pool_exhausted_ = "id-pool-exhausted";
    public static final int    _method = 781988118;
    public static final String _method_ = "method";
    public static final int    _error = 126243105;
    public static final String _error_ = "error";
    public static final int    _firstfree = 1766972967;
    public static final String _firstfree_ = "firstfree";
    public static final int    _low_threshold_alarm = 99736276;
    public static final String _low_threshold_alarm_ = "low-threshold-alarm";
    public static final int    _start = 1011022838;
    public static final String _start_ = "start";
    public static final int    _allocation = 1779434013;
    public static final String _allocation_ = "allocation";
    public static final int    _roundrobin = 2058572782;
    public static final String _roundrobin_ = "roundrobin";
}
