/*
 * BEWARE BEWARE BEWARE BEWARE BEWARE BEWARE BEWARE BEWARE BEWARE
 * This file has been auto-generated by the confdc compiler.
 * Source: ../load-dir/id-allocator-oper.fxs
 * BEWARE BEWARE BEWARE BEWARE BEWARE BEWARE BEWARE BEWARE BEWARE
 */

package com.tailf.pkg.idallocator.namespaces;

import com.tailf.conf.ConfNamespace;

/** Autogenerated namespace class for YANG module id-allocator-oper.yang */
public class idAllocatorOper extends ConfNamespace {
    public static final int hash = 1819087117;
    public int hash() {
        return idAllocatorOper.hash;
    }

    public static final String id = "http://tail-f.com/pkg/id-allocator-oper";
    public String id() {
        return idAllocatorOper.id;
    }

    public static final String uri = "http://tail-f.com/pkg/id-allocator-oper";
    public String uri() {
        return idAllocatorOper.uri;
    }

    public static final String prefix = "idalloc-oper";
    public String prefix() {
        return idAllocatorOper.prefix;
    }

    public idAllocatorOper() {}

    public static int stringToHash(String str) {
        return ConfNamespace.stringToHash(str);
    }

    public static String hashToString(int hash) {
        return ConfNamespace.hashToString(hash);
    }

    public static final int    _exclude = 1901477268;
    public static final String _exclude_ = "exclude";
    public static final int    _available = 162386130;
    public static final String _available_ = "available";
    public static final int    _name = 1998270519;
    public static final String _name_ = "name";
    public static final int    _range = 28853268;
    public static final String _range_ = "range";
    public static final int    _end = 1510734141;
    public static final String _end_ = "end";
    public static final int    _id = 1279252765;
    public static final String _id_ = "id";
    public static final int    _id_allocator = 2092906039;
    public static final String _id_allocator_ = "id-allocator";
    public static final int    _pool = 1920184583;
    public static final String _pool_ = "pool";
    public static final int    _start = 1011022838;
    public static final String _start_ = "start";
    public static final int    _allocation = 1779434013;
    public static final String _allocation_ = "allocation";
}
