/*
 * BEWARE BEWARE BEWARE BEWARE BEWARE BEWARE BEWARE BEWARE BEWARE
 * This file has been auto-generated by the confdc compiler.
 * Source: ../load-dir/ipaddress-allocator-oper.fxs
 * BEWARE BEWARE BEWARE BEWARE BEWARE BEWARE BEWARE BEWARE BEWARE
 */

package com.tailf.pkg.ipaddressallocator.namespaces;

import com.tailf.conf.ConfNamespace;

/** Autogenerated namespace class for YANG module ipaddress-allocator-oper.yang */
public class ipaddressAllocatorOper extends ConfNamespace {
    public static final int hash = 276440424;
    public int hash() {
        return ipaddressAllocatorOper.hash;
    }

    public static final String id = "http://tail-f.com/pkg/ipaddress-allocator-oper";
    public String id() {
        return ipaddressAllocatorOper.id;
    }

    public static final String uri = "http://tail-f.com/pkg/ipaddress-allocator-oper";
    public String uri() {
        return ipaddressAllocatorOper.uri;
    }

    public static final String prefix = "ipalloc-oper";
    public String prefix() {
        return ipaddressAllocatorOper.prefix;
    }

    public ipaddressAllocatorOper() {}

    public static int stringToHash(String str) {
        return ConfNamespace.stringToHash(str);
    }

    public static String hashToString(int hash) {
        return ConfNamespace.hashToString(hash);
    }

    public static final int    _exclude = 1901477268;
    public static final String _exclude_ = "exclude";
    public static final int    _username = 870658415;
    public static final String _username_ = "username";
    public static final int    _available = 162386130;
    public static final String _available_ = "available";
    public static final int    _name = 1998270519;
    public static final String _name_ = "name";
    public static final int    _subnet = 1544472008;
    public static final String _subnet_ = "subnet";
    public static final int    _cidrmask = 40931129;
    public static final String _cidrmask_ = "cidrmask";
    public static final int    _ip_allocator = 1426049540;
    public static final String _ip_allocator_ = "ip-allocator";
    public static final int    _request_id = 1981687022;
    public static final String _request_id_ = "request-id";
    public static final int    _address = 1266954393;
    public static final String _address_ = "address";
    public static final int    _owner = 206925960;
    public static final String _owner_ = "owner";
    public static final int    _pool = 1920184583;
    public static final String _pool_ = "pool";
    public static final int    _allocation = 1779434013;
    public static final String _allocation_ = "allocation";
}
