/*
 * BEWARE BEWARE BEWARE BEWARE BEWARE BEWARE BEWARE BEWARE BEWARE
 * This file has been auto-generated by the confdc compiler.
 * Source: ../load-dir/ipaddress-allocator.fxs
 * BEWARE BEWARE BEWARE BEWARE BEWARE BEWARE BEWARE BEWARE BEWARE
 */

package com.tailf.pkg.ipaddressallocator.namespaces;

import com.tailf.conf.ConfNamespace;

/** Autogenerated namespace class for YANG module ipaddress-allocator.yang */
public class ipaddressAllocator extends ConfNamespace {
    public static final int hash = 2080330223;
    public int hash() {
        return ipaddressAllocator.hash;
    }

    public static final String id = "http://tail-f.com/pkg/ipaddress-allocator";
    public String id() {
        return ipaddressAllocator.id;
    }

    public static final String uri = "http://tail-f.com/pkg/ipaddress-allocator";
    public String uri() {
        return ipaddressAllocator.uri;
    }

    public static final String prefix = "ipalloc";
    public String prefix() {
        return ipaddressAllocator.prefix;
    }

    public ipaddressAllocator() {}

    public static int stringToHash(String str) {
        return ConfNamespace.stringToHash(str);
    }

    public static String hashToString(int hash) {
        return ConfNamespace.hashToString(hash);
    }

    public static final int    _auto_redeploy = 2118496183;
    public static final String _auto_redeploy_ = "auto-redeploy";
    public static final int    _enabled = 197426095;
    public static final String _enabled_ = "enabled";
    public static final int    _alarms = 1907669299;
    public static final String _alarms_ = "alarms";
    public static final int    _exclude = 1901477268;
    public static final String _exclude_ = "exclude";
    public static final int    _username = 870658415;
    public static final String _username_ = "username";
    public static final int    _allocating_service = 38335226;
    public static final String _allocating_service_ = "allocating-service";
    public static final int    _response = 1363637576;
    public static final String _response_ = "response";
    public static final int    _ip_address_pool_exhausted = 1269608959;
    public static final String _ip_address_pool_exhausted_ = "ip-address-pool-exhausted";
    public static final int    _ip_address_pool = 1723584173;
    public static final String _ip_address_pool_ = "ip-address-pool";
    public static final int    _name = 1998270519;
    public static final String _name_ = "name";
    public static final int    _subnet = 1544472008;
    public static final String _subnet_ = "subnet";
    public static final int    _invert_subnet_size = 924726412;
    public static final String _invert_subnet_size_ = "invert-subnet-size";
    public static final int    _cidrmask = 40931129;
    public static final String _cidrmask_ = "cidrmask";
    public static final int    _range = 28853268;
    public static final String _range_ = "range";
    public static final int    _ip_address_allocation_alarm = 2126076405;
    public static final String _ip_address_allocation_alarm_ = "ip-address-allocation-alarm";
    public static final int    _response_choice = 523747723;
    public static final String _response_choice_ = "response-choice";
    public static final int    _ok = 410023581;
    public static final String _ok_ = "ok";
    public static final int    _ip_address_pool_low_threshold_reached = 1239294687;
    public static final String _ip_address_pool_low_threshold_reached_ = "ip-address-pool-low-threshold-reached";
    public static final int    _request = 1788176625;
    public static final String _request_ = "request";
    public static final int    _id = 1279252765;
    public static final String _id_ = "id";
    public static final int    _address = 1266954393;
    public static final String _address_ = "address";
    public static final int    _from = 261037251;
    public static final String _from_ = "from";
    public static final int    _error = 126243105;
    public static final String _error_ = "error";
    public static final int    _to = 809436769;
    public static final String _to_ = "to";
    public static final int    _subnet_size = 241118626;
    public static final String _subnet_size_ = "subnet-size";
    public static final int    _low_threshold_alarm = 99736276;
    public static final String _low_threshold_alarm_ = "low-threshold-alarm";
    public static final int    _allocation = 1779434013;
    public static final String _allocation_ = "allocation";
    public static final String validate_ipa_validate = "ipa_validate";
}
